### ISSUE TITLE
demo paybook fails sso login

### ISSUE THREAD

**Issue by wuftymerguftyguff** [sap-linuxlab/community.sap_launchpad#9]
```failed: [localhost] (item=SAPCAR_1324-80000936.EXE) => {"ansible_loop_var": "item", "changed": false, "item": "SAPCAR_1324-80000936.EXE", "msg": "SAP SSO authentication failed - 401 Client Error:  for url: https://core-api.account.sap.com/uid-core/authenticate?reqId=https%3A%2F%2Fhana.ondemand.com%2Fsupportportal"}```
```failed: [localhost] (item=HCMT_057_0-80003261.SAR) => {"ansible_loop_var": "item", "changed": false, "item": "HCMT_057_0-80003261.SAR", "msg": "SAP SSO authentication failed - 401 Client Error:  for url: https://core-api.account.sap.com/uid-core/authenticate?reqId=https%3A%2F%2Fhana.ondemand.com%2Fsupportportal"}
```

**Comment by rhmk** [comment]
Thabks, for telling. I will double check

Jeff Arthur ***@***.***> schrieb am Do., 2. Feb. 2023, 23:14:

**Comment by rhmk** [comment]
Have you supplies SAP S User credentials with download permission?

Jeff Arthur ***@***.***> schrieb am Do., 2. Feb. 2023, 23:14:

**Comment by wuftymerguftyguff** [comment]
Hi,

Yes I had, but I think I understand the issue now.  I was using the password for the S user not the Universal ID password.

I found this in the docs eventually.

Please close this one sorry to waste your time.

**Comment by sean-freeman** [comment]
@wuftymerguftyguff No trouble :)  Very common mistake, this part of the user/password experience is not clear/distinct from SAP. You can see further examples of this Ansible Collection in heavy usage by the [Terraform Templates for SAP](https://github.com/sap-linuxlab/terraform.templates_for_sap#terraform-templates-for-sap) for now, there will be parity Ansible Playbooks for SAP coming in the near future.
